### ISSUE TITLE
Ninja Forms v3.0 Support

### ISSUE THREAD

**Issue by kjohnson** [wpsight/wpcasa-ninja-forms#1]
Ninja Forms THREE (v3.0) is getting a major overhaul.

This integration will need some updating for compatibility.

**Comment by simonrimkus** [comment]
Hey Kyle,

Thanks for stopping by! Unfortunately I'm a bit backed up and lacking of time right now to update the bridge add-on for Ninja Forms v3.0.

I'm also not sure if I will update it at all as I also especially liked your plugin (up to 2.9) because it used to be embedded into the default WordPress UI and was surprised when I saw your new 3.0 form editor totally moving away from it. Don't get me wrong. It's looking great and maybe better than the WordPress UI. But still, I think plugins should respect it and not _confuse_ the user with different admin layouts.

You probably had these discussions in your team and have good reasons for this decision. But with WPCasa and the plugins we recommend I try stick to the default UI in the backend.

When I had a look at the new version in combination with WPCasa I also had problems with porting the existing forms (e.g. listing contact form). I've read your docs and understand that not all forms could be moved to the new version but in my case these are just some text input and hidden fields.

**Comment by codestylist** [comment]
We have added support for Ninja Form with WPCasa Ninja Forms 2.0.0
